# Generated by Django 2.1.2 on 2018-10-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_item_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
