# Generated by Django 2.1.2 on 2018-10-08 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='code',
            new_name='short_url',
        ),
    ]
