# Generated by Django 2.1.2 on 2018-10-11 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socoolMediaManager', '0002_platformtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='platform_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='socoolMediaManager.PlatformType'),
            preserve_default=False,
        ),
    ]
