# Generated by Django 2.1.2 on 2018-10-11 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socoolMediaManager', '0004_platform_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
