# Generated by Django 2.1.2 on 2018-10-12 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socoolMediaManager', '0005_auto_20181011_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='username',
        ),
    ]
